name: gigya_flutter_plugin
description: SAP Gigya Flutter plugin
version: 0.1.1
homepage: https://github.com/SAP/gigya-flutter-plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  plugin:
    platforms:
      android:
        package: com.sap.gigya_flutter_plugin
        pluginClass: GigyaFlutterPlugin
      ios:
        pluginClass: GigyaFlutterPlugin


